substitutions:
  _PROJECT_ID: "tmp-devops"
  _REGION: "asia-south1"
  _GKE_CLUSTER: "numrah-prod"
  _GKE_ZONE: "asia-south1-a"
options:
  automapSubstitutions: true

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/api-server:1.0.0-$SHORT_SHA', './src/api_server/','-f','./src/api_server/Dockerfile']

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
